package com.voting.dao;

import com.voting.database.DatabaseConnection;
import com.voting.model.Candidate;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * Data-access class for the {@code candidates} table.
 *
 * <p>Every candidate belongs to exactly one election ({@code election_id}),
 * so candidates from different elections are never mixed. Note that
 * {@code candidate_id} is auto-generated by the database, while the existing
 * {@link Candidate} model requires an ID at construction time — so
 * {@link #addCandidate(int, String, String)} accepts plain fields and
 * returns the generated ID, rather than accepting/returning a
 * {@code Candidate} directly for inserts.</p>
 */
public class CandidateDAO {

    /**
     * Registers a new candidate for a specific election.
     *
     * @param electionId     the election this candidate is standing in
     * @param name           candidate's full name
     * @param politicalParty candidate's political party
     * @return the generated {@code candidate_id}
     * @throws SQLException if the insert fails
     */
    public int addCandidate(int electionId, String name, String politicalParty) throws SQLException {
        String sql = "INSERT INTO candidates (election_id, name, political_party) VALUES (?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setInt(1, electionId);
            stmt.setString(2, name);
            stmt.setString(3, politicalParty);
            stmt.executeUpdate();

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getInt(1);
                }
                throw new SQLException("Candidate insert did not return a generated ID.");
            }
        }
    }

    /**
     * Finds a candidate by ID, regardless of which election they belong to.
     *
     * @param candidateId the candidate ID to look up
     * @return a {@link Candidate} built from the stored row, or {@code null} if not found
     * @throws SQLException if the query fails
     */
    public Candidate findByCandidateId(int candidateId) throws SQLException {
        String sql = "SELECT candidate_id, name, political_party FROM candidates WHERE candidate_id = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, candidateId);

            try (ResultSet rs = stmt.executeQuery()) {
                return rs.next() ? mapRow(rs) : null;
            }
        }
    }

    /**
     * Returns all candidates standing in a specific election.
     *
     * @param electionId the election to look up candidates for
     * @return list of candidates in that election (empty list if none)
     * @throws SQLException if the query fails
     */
    public List<Candidate> getCandidatesForElection(int electionId) throws SQLException {
        String sql = "SELECT candidate_id, name, political_party FROM candidates WHERE election_id = ?";

        List<Candidate> candidates = new ArrayList<>();

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, electionId);

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    candidates.add(mapRow(rs));
                }
            }
        }
        return candidates;
    }

    /**
     * Checks whether a candidate exists within a specific election.
     *
     * @param electionId  the election to check within
     * @param candidateId the candidate ID to check
     * @return {@code true} if that candidate exists in that election
     * @throws SQLException if the query fails
     */
    public boolean candidateExists(int electionId, int candidateId) throws SQLException {
        String sql = "SELECT 1 FROM candidates WHERE election_id = ? AND candidate_id = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, electionId);
            stmt.setInt(2, candidateId);

            try (ResultSet rs = stmt.executeQuery()) {
                return rs.next();
            }
        }
    }

    private Candidate mapRow(ResultSet rs) throws SQLException {
        return new Candidate(
                String.valueOf(rs.getInt("candidate_id")),
                rs.getString("name"),
                rs.getString("political_party")
        );
    }
}
